title: <p align="center"> Surin Suresh </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://in.linkedin.com/in/surin-suresh-99ab64162">LinkedIn</a> |
  <a href="https://github.com/surinsuresh">GitHub</a>
  
  <br>   
  I am working as a project coordinator at Lucid Imaging with a 4 years of experience in the field of machine vision and Image processing. 
  <br>
  </p>



theme: jekyll-theme-minimal
